// <auto-generated />
using System;
using Banha_UniverCity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banha_UniverCity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241212120154_edit_studentId_in_progress_table")]
    partial class edit_studentId_in_progress_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BFCAI.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseCurriculumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("CourseCurriculumID");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("BFCAI.Models.AssignmentSubmission", b =>
                {
                    b.Property<int>("AssignmentSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentSubmissionID"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AssignmentSubmissionID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("AssignmentID");

                    b.ToTable("AssignmentSubmissions");
                });

            modelBuilder.Entity("BFCAI.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseCurriculumID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("CourseCurriculumID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("BFCAI.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BFCAI.Models.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CourseId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BFCAI.Models.CourseResource", b =>
                {
                    b.Property<int>("CourseResourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseResourceID"));

                    b.Property<int?>("CourseCurriculumID")
                        .HasColumnType("int");

                    b.Property<string>("ResourceTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseResourceID");

                    b.HasIndex("CourseCurriculumID");

                    b.ToTable("CourseResources");
                });

            modelBuilder.Entity("BFCAI.Models.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamID");

                    b.HasIndex("CourseID");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            ExamID = 1,
                            CourseID = 1,
                            ExamDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = "1",
                            Title = "Math Final Exam"
                        },
                        new
                        {
                            ExamID = 2,
                            CourseID = 2,
                            ExamDate = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = "2",
                            Title = "Physics Final Exam"
                        });
                });

            modelBuilder.Entity("BFCAI.Models.ExamSubmission", b =>
                {
                    b.Property<int>("ExamSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamSubmissionID"));

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamSubmissionID");

                    b.HasIndex("ExamID");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamSubmissions");
                });

            modelBuilder.Entity("BFCAI.Models.KeyWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("BFCAI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("OrderStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BFCAI.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BFCAI.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.HasIndex("ExamID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            ExamID = 1,
                            QuestionText = "What is 2 + 2?"
                        },
                        new
                        {
                            QuestionID = 2,
                            ExamID = 2,
                            QuestionText = "What is the speed of light?"
                        });
                });

            modelBuilder.Entity("BFCAI.Models.QuestionChoice", b =>
                {
                    b.Property<int>("QuestionChoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionChoiceID"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuestionChoiceID");

                    b.HasIndex("QuestionID");

                    b.ToTable("QuestionChoices");

                    b.HasData(
                        new
                        {
                            QuestionChoiceID = 1,
                            ChoiceText = "4",
                            IsCorrect = true,
                            QuestionID = 1
                        },
                        new
                        {
                            QuestionChoiceID = 2,
                            ChoiceText = "3",
                            IsCorrect = false,
                            QuestionID = 1
                        },
                        new
                        {
                            QuestionChoiceID = 3,
                            ChoiceText = "299,792 km/s",
                            IsCorrect = true,
                            QuestionID = 2
                        },
                        new
                        {
                            QuestionChoiceID = 4,
                            ChoiceText = "150,000 km/s",
                            IsCorrect = false,
                            QuestionID = 2
                        });
                });

            modelBuilder.Entity("BFCAI.Models.StudentCourseProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourseProgress");
                });

            modelBuilder.Entity("BFCAI.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearID"));

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcademicYearID");

                    b.ToTable("AcademicYear");

                    b.HasData(
                        new
                        {
                            AcademicYearID = 1,
                            YearName = "2020-2021"
                        },
                        new
                        {
                            AcademicYearID = 2,
                            YearName = "2021-2022"
                        },
                        new
                        {
                            AcademicYearID = 3,
                            YearName = "2022-2023"
                        },
                        new
                        {
                            AcademicYearID = 4,
                            YearName = "2023-2024"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.ClassSchedule", b =>
                {
                    b.Property<int>("ClassScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassScheduleId"));

                    b.Property<int?>("AcadmicYearId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ClassScheduleId");

                    b.HasIndex("AcadmicYearId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("RoomId");

                    b.ToTable("ClassSchedule");

                    b.HasData(
                        new
                        {
                            ClassScheduleId = 1,
                            CourseId = 1,
                            DayOfWeek = "Monday",
                            EndTime = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = "1",
                            RoomId = 1,
                            StartTime = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassScheduleId = 2,
                            CourseId = 2,
                            DayOfWeek = "Tuesday",
                            EndTime = new DateTime(2024, 10, 1, 10, 2, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = "2",
                            RoomId = 2,
                            StartTime = new DateTime(2024, 10, 1, 10, 2, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("DemoVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NumOfEnrollments")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrackID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TrackID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseName = "Introduction to Programming",
                            Credits = 0,
                            DemoVideoUrl = "",
                            DepartmentId = 1,
                            Description = "",
                            InstructorId = "2"
                        },
                        new
                        {
                            CourseID = 2,
                            CourseName = "Digital Circuits",
                            Credits = 0,
                            DemoVideoUrl = "",
                            DepartmentId = 2,
                            Description = "",
                            InstructorId = "2"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.CourseCurriculum", b =>
                {
                    b.Property<int>("CourseCurriculumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCurriculumID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseCurriculumID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseCurricula");

                    b.HasData(
                        new
                        {
                            CourseCurriculumID = 1,
                            Content = "Intro Of Cs",
                            CourseID = 1,
                            Title = "Introduction"
                        },
                        new
                        {
                            CourseCurriculumID = 2,
                            Content = "Intro Of C++",
                            CourseID = 2,
                            Title = "Basic Programming Concepts"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.CourseVideo", b =>
                {
                    b.Property<int>("CourseVideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseVideoID"));

                    b.Property<int?>("CourseCurriculumID")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseVideoID");

                    b.HasIndex("CourseCurriculumID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseVideos");

                    b.HasData(
                        new
                        {
                            CourseVideoID = 1,
                            CourseID = 1,
                            VideoTitle = "Course Overview",
                            VideoURL = "http://example.com/video1"
                        },
                        new
                        {
                            CourseVideoID = 2,
                            CourseID = 1,
                            VideoTitle = "Getting Started",
                            VideoURL = "http://example.com/video2"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Cover = "",
                            DepartmentDescription = "",
                            DepartmentName = "Computer Science"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Cover = "",
                            DepartmentDescription = "",
                            DepartmentName = "Electrical Engineering"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentID = 1,
                            CourseID = 1,
                            StudentId = "1"
                        },
                        new
                        {
                            EnrollmentID = 2,
                            CourseID = 2,
                            StudentId = "1"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetStudentUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProviderUserId");

                    b.HasIndex("TargetStudentUserId");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            FeedbackID = 1,
                            Content = "Great course!",
                            CourseId = 1,
                            FeedbackDate = new DateTime(2024, 12, 12, 14, 1, 48, 190, DateTimeKind.Local).AddTicks(7149),
                            ProviderUserId = "1",
                            TargetStudentUserId = "1"
                        },
                        new
                        {
                            FeedbackID = 2,
                            Content = "Need improvement on some topics.",
                            CourseId = 2,
                            FeedbackDate = new DateTime(2024, 12, 12, 14, 1, 48, 190, DateTimeKind.Local).AddTicks(7231),
                            ProviderUserId = "2",
                            TargetStudentUserId = "1"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.LearningObjective", b =>
                {
                    b.Property<int>("LearningObjectiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningObjectiveID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LearningObjectiveID");

                    b.HasIndex("CourseID");

                    b.ToTable("LearningObjective");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Capacity = 30,
                            Name = "Room 101"
                        },
                        new
                        {
                            RoomID = 2,
                            Capacity = 20,
                            Name = "Lab 202"
                        });
                });

            modelBuilder.Entity("Banha_UniverCity.Models.TopicCovered", b =>
                {
                    b.Property<int>("TopicCoveredID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicCoveredID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicCoveredID");

                    b.HasIndex("CourseID");

                    b.ToTable("TopicCovered");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "123548458",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Banha_UniverCity.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<int?>("AvailableCreditHours")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7ecdf03-cbe1-480f-a194-988e659b776a",
                            Email = "student1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@EXAMPLE.COM",
                            NormalizedUserName = "STUDENT1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aa1e1f0f-fa87-4abb-841b-f26214a7be8e",
                            TwoFactorEnabled = false,
                            UserName = "student1",
                            AvailableCreditHours = 0,
                            FullName = "Student One",
                            Picture = "",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe687040-8687-48a8-b730-827f0639c40c",
                            Email = "instructor1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "INSTRUCTOR1@EXAMPLE.COM",
                            NormalizedUserName = "INSTRUCTOR1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6e681bf7-0d94-45bc-b335-1b254b99a336",
                            TwoFactorEnabled = false,
                            UserName = "instructor1",
                            AvailableCreditHours = 0,
                            FullName = "Instructor One",
                            Picture = "",
                            UserType = "Instructor"
                        },
                        new
                        {
                            Id = "123548458",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c964e96-1c3a-445f-90e1-42b8b7e3c6a4",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFC7XsB3YM72DE2ZMA8gLtMj26nKA0aNNtzeeW9VYAvp5ylFcK6LWoDKOHJhErp1Sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c73e84f-1701-4a01-9ad6-ec5fa0e6f16c",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com",
                            AvailableCreditHours = 0,
                            FullName = "Admin",
                            Picture = "",
                            UserType = "Admin"
                        });
                });

            modelBuilder.Entity("BFCAI.Models.Assignment", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.CourseCurriculum", "CourseCurriculum")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseCurriculumID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseCurriculum");
                });

            modelBuilder.Entity("BFCAI.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BFCAI.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("BFCAI.Models.Attendance", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Attendances")
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banha_UniverCity.Models.CourseCurriculum", "CourseCurriculum")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseCurriculumID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CourseCurriculum");
                });

            modelBuilder.Entity("BFCAI.Models.Cart", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BFCAI.Models.CartItems", b =>
                {
                    b.HasOne("BFCAI.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BFCAI.Models.CourseResource", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.CourseCurriculum", "CourseCurriculum")
                        .WithMany("CourseResources")
                        .HasForeignKey("CourseCurriculumID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CourseCurriculum");
                });

            modelBuilder.Entity("BFCAI.Models.Exam", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banha_UniverCity.Models.CourseCurriculum", "CourseCurriculum")
                        .WithMany("Exams")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Instructor")
                        .WithMany("Exams")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("CourseCurriculum");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("BFCAI.Models.ExamSubmission", b =>
                {
                    b.HasOne("BFCAI.Models.Exam", "Exam")
                        .WithMany("ExamSubmissions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Student")
                        .WithMany("ExamSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BFCAI.Models.KeyWord", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("Keywords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BFCAI.Models.Order", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BFCAI.Models.OrderItems", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BFCAI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BFCAI.Models.Question", b =>
                {
                    b.HasOne("BFCAI.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("BFCAI.Models.QuestionChoice", b =>
                {
                    b.HasOne("BFCAI.Models.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BFCAI.Models.StudentCourseProgress", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("StudentCourseProgresses")
                        .HasForeignKey("CourseId");

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Student")
                        .WithMany("StudentCourseProgresses")
                        .HasForeignKey("StudentId");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.ClassSchedule", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.AcademicYear", "AcadmicYear")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("AcadmicYearId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banha_UniverCity.Models.Department", "Department")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Instructor")
                        .WithMany("Schedules")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Banha_UniverCity.Models.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcadmicYear");

                    b.Navigation("Course");

                    b.Navigation("Department");

                    b.Navigation("Instructor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Course", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Instructor")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BFCAI.Models.Track", "Track")
                        .WithMany("Courses")
                        .HasForeignKey("TrackID");

                    b.Navigation("Department");

                    b.Navigation("Instructor");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.CourseCurriculum", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("CourseCurricula")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.CourseVideo", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.CourseCurriculum", "CourseCurriculum")
                        .WithMany("CourseVideos")
                        .HasForeignKey("CourseCurriculumID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("CourseVideos")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseCurriculum");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Enrollment", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Event", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Banha_UniverCity.Models.Department", "Department")
                        .WithMany("Events")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Feedback", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseId");

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "ProviderUser")
                        .WithMany("FeedbacksGiven")
                        .HasForeignKey("ProviderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banha_UniverCity.Models.ApplicationUser", "TargetStudentUser")
                        .WithMany("FeedbacksReceived")
                        .HasForeignKey("TargetStudentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ProviderUser");

                    b.Navigation("TargetStudentUser");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.LearningObjective", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("LearningObjectives")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.TopicCovered", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.Course", "Course")
                        .WithMany("TopicsCovered")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banha_UniverCity.Models.ApplicationUser", b =>
                {
                    b.HasOne("Banha_UniverCity.Models.AcademicYear", "AcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("AcademicYearID");

                    b.HasOne("Banha_UniverCity.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BFCAI.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BFCAI.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BFCAI.Models.Exam", b =>
                {
                    b.Navigation("ExamSubmissions");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BFCAI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BFCAI.Models.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("BFCAI.Models.Track", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.AcademicYear", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Course", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("CourseCurricula");

                    b.Navigation("CourseVideos");

                    b.Navigation("Enrollments");

                    b.Navigation("Exams");

                    b.Navigation("Feedbacks");

                    b.Navigation("Keywords");

                    b.Navigation("LearningObjectives");

                    b.Navigation("StudentCourseProgresses");

                    b.Navigation("TopicsCovered");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.CourseCurriculum", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attendances");

                    b.Navigation("CourseResources");

                    b.Navigation("CourseVideos");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Department", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("Courses");

                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Banha_UniverCity.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("Attendances");

                    b.Navigation("Carts");

                    b.Navigation("CoursesTaught");

                    b.Navigation("Enrollments");

                    b.Navigation("Events");

                    b.Navigation("ExamSubmissions");

                    b.Navigation("Exams");

                    b.Navigation("FeedbacksGiven");

                    b.Navigation("FeedbacksReceived");

                    b.Navigation("Orders");

                    b.Navigation("Schedules");

                    b.Navigation("StudentCourseProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
